
source "https://github.com/CocoaPods/Specs.git"
source "https://git.coding.net/AaronTang/TJPSegementSpecs.git"

platform :ios, '8.0'

target 'TJPYingKe' do
  use_frameworks!

pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'Masonry'
pod 'SDCycleScrollView'


pod 'TJPSengment', '~> 0.1.0'


end
